### ISSUE TITLE
Fluids registered too late

### ISSUE THREAD

**Issue by Haggle1996** [jaredlll08/ContentTweaker#4]
Anything I can do about this?

```
[11:27:57] [Server thread/INFO] [STDOUT/MineTweaker3]: [minetweaker.runtime.MTTweaker:load:156]: MineTweaker: Loading 1TiCon.zs
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: ****************************************
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: * The object contentTweaker.content.fluids.FluidCustom@30eefdb5 (name MineTweaker3:molten.chromaalloy) is being added too late.
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:399)
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:894)
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:869)
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:229)
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177)...
[11:27:58] [Server thread/WARN] [FML/MineTweaker3]: ****************************************
```

**Comment by jaredlll08** [comment]
Eh, I never experienced it, I'll get a new version up eventually with a fix

**Comment by bookerthegeek** [comment]
Can I see the script?

**Comment by Haggle1996** [comment]
Pretty straightforward.

```
# Materials in order
# 1 Chroma Alloy <ChromatiCraft:chromaticraft_item_crafting:11>
mods.content.Material.registerMaterial("chromaalloy", "Chroma Alloy", "§4", <ChromatiCraft:chromaticraft_item_crafting:11>, 55, 3, 1100, 600, 6, 1, 16750548, 2, 1.8, 0, false, 0, "", 1.0, 1.2, 7, 10, null, ["81 5"]);
mods.content.Fluid.registerFluid("molten.chromaalloy", 100, false, 15, 80, 100, 16750548, false, 55, "molten_chroma");
```

This is 1.7.10, btw.

**Comment by jaredlll08** [comment]
wait... @Haggle1996 forgot to ask... where is the script being put?

**Comment by Haggle1996** [comment]
It's in /scripts/1Tico.zs -- lemme guess, needs to be in ContentTweaker?

**Comment by jaredlll08** [comment]
Yea... put it in "/contentScripts/"

That was mentioned in the curse post.

**Comment by Haggle1996** [comment]
I have the script loading now, in the correct folder. However, I receive the following error during load. It does not matter in which order the two lines above are located in the script file. The fluid and material both register, but their casting recipes are never created (the items are).

```
[12:50:04] [Client thread/WARN] [FML/TConstruct]: ****************************************
[12:50:04] [Client thread/WARN] [FML/TConstruct]: * Casting IMC: Unknown Material ID 55
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at tconstruct.util.IMCHandler.processIMC(IMCHandler.java:182)
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at tconstruct.TConstruct.handleIMC(TConstruct.java:246)
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:50:04] [Client thread/WARN] [FML/TConstruct]: *  at java.lang.reflect.Method.invoke(Unknown Source)...
[12:50:04] [Client thread/WARN] [FML/TConstruct]: ****************************************
[12:50:04] [Client thread/DEBUG] [TConstruct/TConstruct]: IMC: Added material chromaalloy
[12:50:04] [Client thread/DEBUG] [TConstruct/TConstruct]: IMC: Added Bow stats for material chromaalloy
[12:50:04] [Client thread/DEBUG] [TConstruct/TConstruct]: IMC: Added Projectile stats for material chromaalloy
```

**Comment by jaredlll08** [comment]
Very weird, honestly no idea
